# https://dart.dev/get-dart#install-a-debian-package
RUN apt install wget -y
RUN wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_3.3.3-1_amd64.deb
RUN dpkg -i dart_3.3.3-1_amd64.deb
RUN apt install -f -y
RUN rm dart_3.3.3-1_amd64.deb