RUN apt update && \
VERSION=6.0.0 && \
curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl_${VERSION}_amd64.deb && \
apt install ./hurl_${VERSION}_amd64.deb && \
rm ./hurl_${VERSION}_amd64.deb