### Android
# https://github.com/thyrlian/AndroidSDK
FROM thyrlian/android-sdk:9.3

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends --no-install-suggests ca-certificates \
    && update-ca-certificates